#!/usr/bin/env bash
# Output: The subdomain [SUB_DOMAIN] is a 
# [RECORD_TYPE] record and points to [DESTINATION]

list=(www lb-01 web-01 web-02)
args=$#

SubdomainRecords()
{
	if [ $args == 2 ]
	then
		rec=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf "%s", $4;} END {print ""}')
		dest=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf "%s", $5;} END {print ""}')
		echo "The subdomain $2 is a $rec record and points to $dest"
	else
		for i in "${!list[@]}"; do
			rec=$(dig "${list[$i]}"."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf "%s", $4;} END {print ""}')
			dest=$(dig "${list[$i]}"."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf "%s", $5;} END {print ""}')
			echo "The subdomain ${list[$i]} is a $rec record and points to $dest"
		done
	fi
}
SubdomainRecords "$1" "$2"
