#!/usr/bin/env bash
# redirect a file

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v\=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
