#!/usr/bin/env bash
# modify the nginx.config file
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Hello World!" > /var/www/html/index.html
sudo sed -i 23i'\\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
